// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameTick = __t.object("GameTick", {
  scheduledId: __t.u64(),
  roomId: __t.string(),
  scheduledAt: __t.scheduleAt(),
});
export type GameTick = __Infer<typeof GameTick>;

export const Knibble = __t.object("Knibble", {
  id: __t.u64(),
  roomId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  size: __t.f64(),
  color: __t.string(),
});
export type Knibble = __Infer<typeof Knibble>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  roomId: __t.string(),
  name: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  radius: __t.f64(),
  velX: __t.f64(),
  velY: __t.f64(),
  inputX: __t.f64(),
  inputY: __t.f64(),
  color: __t.string(),
  skinId: __t.option(__t.string()),
  score: __t.u32(),
  isAlive: __t.bool(),
  lastSplitAt: __t.i64(),
  lastSpitAt: __t.i64(),
  joinedAt: __t.i64(),
});
export type Player = __Infer<typeof Player>;

export const PlayerResult = __t.object("PlayerResult", {
  id: __t.string(),
  roomId: __t.string(),
  playerIdentity: __t.identity(),
  name: __t.string(),
  color: __t.string(),
  placement: __t.u32(),
  finalSize: __t.f64(),
  finalScore: __t.u32(),
  joinedAt: __t.i64(),
  eliminatedAt: __t.i64(),
  wasWinner: __t.bool(),
});
export type PlayerResult = __Infer<typeof PlayerResult>;

export const Room = __t.object("Room", {
  id: __t.string(),
  mode: __t.string(),
  status: __t.string(),
  hostIdentity: __t.option(__t.identity()),
  countdownEndsAt: __t.option(__t.i64()),
  startedAt: __t.option(__t.i64()),
  endedAt: __t.option(__t.i64()),
  durationMs: __t.u32(),
  maxPlayers: __t.u32(),
  minPlayers: __t.u32(),
  winnerIdentity: __t.option(__t.identity()),
  lastUpdateAt: __t.i64(),
  boundsX: __t.f64(),
  boundsY: __t.f64(),
  boundsWidth: __t.f64(),
  boundsHeight: __t.f64(),
});
export type Room = __Infer<typeof Room>;

export const SpitBlob = __t.object("SpitBlob", {
  id: __t.u64(),
  roomId: __t.string(),
  ownerIdentity: __t.identity(),
  x: __t.f64(),
  y: __t.f64(),
  velX: __t.f64(),
  velY: __t.f64(),
  size: __t.f64(),
  createdAt: __t.i64(),
});
export type SpitBlob = __Infer<typeof SpitBlob>;

