// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  roomId: __t.string().name("room_id"),
  name: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  radius: __t.f64(),
  velX: __t.f64().name("vel_x"),
  velY: __t.f64().name("vel_y"),
  inputX: __t.f64().name("input_x"),
  inputY: __t.f64().name("input_y"),
  color: __t.string(),
  score: __t.u32(),
  isAlive: __t.bool().name("is_alive"),
  lastSplitAt: __t.i64().name("last_split_at"),
  lastSpitAt: __t.i64().name("last_spit_at"),
  joinedAt: __t.i64().name("joined_at"),
});
