// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  status: __t.string(),
  hostIdentity: __t.option(__t.identity()).name("host_identity"),
  countdownEndsAt: __t.option(__t.i64()).name("countdown_ends_at"),
  startedAt: __t.option(__t.i64()).name("started_at"),
  endedAt: __t.option(__t.i64()).name("ended_at"),
  durationMs: __t.u32().name("duration_ms"),
  maxPlayers: __t.u32().name("max_players"),
  minPlayers: __t.u32().name("min_players"),
  winnerIdentity: __t.option(__t.identity()).name("winner_identity"),
  lastUpdateAt: __t.i64().name("last_update_at"),
  boundsX: __t.f64().name("bounds_x"),
  boundsY: __t.f64().name("bounds_y"),
  boundsWidth: __t.f64().name("bounds_width"),
  boundsHeight: __t.f64().name("bounds_height"),
});
