// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import JoinGameReducer from "../join_game_reducer";
import LeaveGameReducer from "../leave_game_reducer";
import SetInputReducer from "../set_input_reducer";
import SpitReducer from "../spit_reducer";
import SplitReducer from "../split_reducer";
import StartGameReducer from "../start_game_reducer";

export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type LeaveGameParams = __Infer<typeof LeaveGameReducer>;
export type SetInputParams = __Infer<typeof SetInputReducer>;
export type SpitParams = __Infer<typeof SpitReducer>;
export type SplitParams = __Infer<typeof SplitReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;

